# Generated by Django 6.0 on 2025-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_mpesatransaction_merchant_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
